### ISSUE TITLE
Counter shows a vatiable on the slots available 

### ISSUE THREAD

**Issue by gabegon8910** [FlorianSW/discord-player-count-bot#14]
I have one server that it shows the variable rather than the number of slots available

x/${status.maxPlayers}$queuedPlayers

![image](https://github.com/user-attachments/assets/269f5d5d-565a-4567-bd6b-0def8b79c8a0)

**Comment by FlorianSW** [comment]
What game is that and can you show me the configuration you used for that (except any sensitive data, if any)? :)

**Comment by FlorianSW** [comment]
The latest version should fix this issue. If you're running with the prebuilt docker image, wait until the Action is through (and green): https://github.com/FlorianSW/discord-player-count-bot/actions/runs/12260886038
